# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package
on: [pull_request] 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #        pip install -r requirements.txt
   
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
  style:
    runs-on: ubuntu-latest  
    
    steps:
      - uses: actions/checkout@v2
      - name: Yapify styling   
      - run: |
           pip install yapf
           yapf test.py
   
#   - name: Test with pytest
#      run: |
#        pip install pytest
#        pytest
        
  deploy:     
       runs-on: ubuntu-latest
       needs: [build]
       
       env:
        AZURE_SA_ID: ${{ secrets.AZURE_SA_ID }}
        AZURE_SA_KEY: ${{ secrets.AZURE_SA_KEY }}
        TENANT: "Naspers.onmicrosoft.com"
       
       steps:
         - uses: actions/checkout@v2
         - name: Install Azure CLI
           run: |
             # Get packages needed for the install process
               sudo apt-get update
               sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
             
             # Download and install the Microsoft signing key
               curl -sL https://packages.microsoft.com/keys/microsoft.asc |
               gpg --dearmor |
               sudo tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null
             
             # Add the Azure CLI software repository
               AZ_REPO=$(lsb_release -cs)
               echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
               sudo tee /etc/apt/sources.list.d/azure-cli.list
             
             # Update repository information and install the azure-cli package:
               sudo apt-get update
               sudo apt-get install azure-cli
               
         - name: Authenticate to Azure CLI
           run: az login --service-principal -u "$AZURE_SA_ID" -p "$AZURE_SA_KEY" --tenant "$TENANT"
         
         - name: Deploy files
           run:
              az storage blob upload --account-name customerhub --container-name testing --name test.py --file test.py --auth-mode login



